[package]
name = "monkeytype-rs"
version = "0.1.0"
edition = "2021"
authors = ["joyanedel <iamjoyanedel@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
tui = "0.19.0"
